from __future__ import annotations  # noqa: D100

from typing import Any

from app.core.models.ui import UnifiedCard
from app.domains.ai.service import (
    AICompanyAnalysis,
    AIContactAnalysis,
    AIDealAnalysis,
    AILeadAnalysis,
)

from .components import ComponentsMixin

MAX_LIST_DISPLAY = 25
MAX_OWNERS_DISPLAY = 100


class InsightsCardsMixin(ComponentsMixin):
    def build_record_insights(self, analysis: Any) -> UnifiedCard:  # noqa: PLR0912, PLR0915
        """Builds a UnifiedCard representation for generic record insights."""
        subtitle = "Insights"
        emoji = "📋"

        type_name = type(analysis).__name__
        if "Contact" in type_name:
            subtitle = "Contact Insights"
            emoji = "👤"
        elif "Deal" in type_name:
            subtitle = "Deal Insights"
            emoji = "💰"
        elif "Company" in type_name:
            subtitle = "Company Insights"
            emoji = "🏢"
        elif "Lead" in type_name:
            subtitle = "Lead Insights"
            emoji = "🎯"
        elif "Ticket" in type_name:
            subtitle = "Ticket Insights"
            emoji = "🎫"
        elif "Engagement" in type_name:
            subtitle = "Engagement Insights"
            emoji = "📞"

        summary = getattr(analysis, "insight", "")
        next_action = getattr(analysis, "next_best_action", "")
        reasoning = getattr(analysis, "engagement_factors", "") or getattr(
            analysis, "next_action_reason", ""
        )

        secondary = []
        if next_action:
            secondary.append(("Next Action", next_action))
        if reasoning:
            secondary.append(("Engagement Factors", reasoning))

        # Build metrics
        metrics: list[tuple[str, str]] = []

        # New: Advanced Sentiment Diagnostics (Rolling Pulse vs Baseline)
        pulse = getattr(analysis, "pulse_score", None)
        baseline = getattr(analysis, "baseline_score", None)

        def _get_sentiment_label(s: int) -> str:
            if s >= 70:
                return "🟢 Positive"  # noqa: E701
            if s >= 40:
                return "🟡 Neutral"  # noqa: E701
            return "🔴 At Risk"

        if pulse is not None:
            metrics.append(("Rolling Pulse", _get_sentiment_label(pulse)))
        if baseline is not None:
            metrics.append(("Historical Baseline", _get_sentiment_label(baseline)))

        # Fallback for generic scores if pulse/baseline not present
        score = getattr(analysis, "score", None)
        if score is not None and pulse is None:
            metrics.append(("Profile Score", _get_sentiment_label(score)))

        health = getattr(analysis, "health", None)
        if health is not None:
            metrics.append(("Health", str(health)))
        risk = getattr(analysis, "risk", None)
        if risk is not None:
            metrics.append(("Risk", str(risk)))
        status_label = getattr(analysis, "status_label", None)
        if status_label is not None:
            metrics.append(("Status", str(status_label)))
        ticket_status = getattr(analysis, "ticket_status", None)
        if ticket_status is not None:
            metrics.append(("Status", str(ticket_status)))
        urgency = getattr(analysis, "urgency", None)
        if urgency is not None:
            metrics.append(("Urgency", str(urgency)))
        sla_label = getattr(analysis, "sla_label", None)
        if sla_label is not None:
            metrics.append(("SLA Status", str(sla_label)))

        return UnifiedCard(
            title="CRM Insights",
            subtitle=subtitle,
            emoji=emoji,  # Maintains the object icon (👤/💰/🏢)
            content=summary,
            metrics=metrics,
            secondary_content=secondary,
            status=getattr(analysis, "status", None),
            footer=f"Sentiment based on last 50 customer interactions • {subtitle}",
        )

    def build_score_analysis(self, analysis: Any) -> UnifiedCard:
        """Builds a UnifiedCard representation for profile score analysis."""
        score = getattr(analysis, "score", "N/A")
        reason = getattr(analysis, "score_reason", "No scoring data available.")

        return UnifiedCard(
            title="Profile Score",
            subtitle="Scoring Analysis",
            emoji="📊",
            metrics=[
                ("Sentiment Score", str(score)),
            ],
            content=reason,
            footer="Generated by REHA's Sovereign AI Engine",
        )

    def build_next_best_action(self, analysis: AIContactAnalysis) -> UnifiedCard:
        """Builds a UnifiedCard representation for the next best action."""
        return UnifiedCard(
            title="Next Best Action",
            subtitle="Recommendation",
            emoji="🎯",
            content=analysis.next_best_action,
            secondary_content=[
                ("Engagement Factors", analysis.next_action_reason),
            ],
            footer="Powered by REHA's Sovereign AI Engine",
        )

    def build_company_insights(self, analysis: AICompanyAnalysis) -> UnifiedCard:
        """Builds a UnifiedCard for Company-specific record insights.

        Args:
            analysis (AICompanyAnalysis): The company analysis data.

        Returns:
            UnifiedCard: The rendered IR.

        """
        secondary = [
            ("Next Action", analysis.next_best_action),
        ]

        if analysis.top_actions:
            actions_text = "\n".join(f"• {action}" for action in analysis.top_actions)
            secondary.append(("Top Next Best Actions for Contacts", actions_text))

        return UnifiedCard(
            title="Company Insights",
            emoji="🏢",
            content=analysis.insight,
            secondary_content=secondary,
            status=analysis.status,
            footer="Insights powered by REHA's Sovereign AI Sentiment Engine (Local Processing)",  # noqa: E501
        )

    def build_deal_insights(self, analysis: AIDealAnalysis) -> UnifiedCard:
        """Builds a UnifiedCard for Deal-specific record insights.

        Args:
            analysis (AIDealAnalysis): The deal analysis data.

        Returns:
            UnifiedCard: The rendered IR.

        """
        secondary = [
            ("Next Action", analysis.next_best_action),
        ]

        if analysis.top_actions:
            actions_text = "\n".join(f"• {action}" for action in analysis.top_actions)
            secondary.append(("Top Next Best Actions for Contacts", actions_text))

        return UnifiedCard(
            title="Deal Insights",
            emoji="💰",
            content=analysis.insight,
            secondary_content=secondary,
            status=analysis.status,
            footer="Insights powered by REHA's Sovereign AI Sentiment Engine (Local Processing)",  # noqa: E501
        )

    def build_lead_insights(self, analysis: AILeadAnalysis) -> UnifiedCard:
        """Builds a UnifiedCard for Lead-specific record insights."""
        return UnifiedCard(
            title="Lead Insights",
            subtitle="Prospect Analysis",
            emoji="🎯",
            content=analysis.insight,
            metrics=[
                ("Sentiment Score", str(analysis.score)),
                ("Status", analysis.status_label),
            ],
            secondary_content=[
                ("Next Action", analysis.next_best_action),
            ],
            footer="Insights powered by REHA's Sovereign AI Sentiment Engine (Local Processing)",  # noqa: E501
        )
